# Generated by Django 6.0.3 on 2026-03-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('survived', models.IntegerField()),
                ('pclass', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.FloatField(blank=True, null=True)),
                ('sibsp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('ticket', models.CharField(max_length=100)),
                ('fare', models.FloatField(blank=True, null=True)),
                ('cabin', models.CharField(blank=True, max_length=100, null=True)),
                ('embarked', models.CharField(blank=True, max_length=100, null=True)),
                ('boat', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.IntegerField(blank=True, null=True)),
                ('home_dest', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
