# Generated by Django 6.0.4 on 2026-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('times_listed', models.IntegerField(default=0)),
                ('num_reviews', models.IntegerField(default=0)),
                ('plays', models.IntegerField(default=0)),
                ('playing', models.IntegerField(default=0)),
                ('backlogs', models.IntegerField(default=0)),
                ('wishlist', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
