# Generated by Django 6.0.4 on 2026-05-03 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('predicted_rating', models.FloatField()),
                ('times_listed', models.IntegerField()),
                ('num_reviews', models.IntegerField()),
                ('plays', models.IntegerField()),
                ('playing', models.IntegerField()),
                ('backlogs', models.IntegerField()),
                ('wishlist', models.IntegerField()),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('actual_rating', models.FloatField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(blank=True, help_text='Actual rating (0-5)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='game',
            name='used_for_training',
            field=models.BooleanField(default=False),
        ),
    ]
