# Generated by Django 6.0.4 on 2026-05-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictionhistory_game_rating_game_used_for_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='used_for_training',
        ),
    ]
